<?php

/**
 * @file
 * Contains church_entity.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function church_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the church_entity module.
    case 'help.page.church_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create a content entity wish church.') . '</p>';
      return $output;

    default:
  }
}
