<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * 修改Drupal.Settings
 * HOOK_js_settings_alter
 */
function progress_field_js_settings_alter(array &$settings, AttachedAssetsInterface $assets) {
    # 去除删除按钮的X-Progress-ID参数，防止删除文件出错
    if(isset($settings['ajax'])) {
        foreach($settings['ajax'] as $k => $v) {
            if(strpos($k, 'remove-button') > 0) {
                $settings['ajax'][$k]['url'] = preg_replace('/\&X\-Progress\-ID\=\d+/', '', $v['url']);
            }
        }
    }
}

/**
 * 修改某个字段插件的属性，行为靠前
 * HOOK_field_widget_WIDGET_TYPE_form_alter
 * WIDGET_TYPE 参考 https://api.drupal.org/comment/60724#comment-60724
 */
#function progress_field_field_widget_file_generic_progress_form_alter(&$element, FormStateInterface $form_state, $context) {
#}

/**
 * 添加上传进度的session标记
 * HOOK_field_widget_WIDGET_TYPE_form_alter
 * WIDGET_TYPE 参考 https://api.drupal.org/comment/60724#comment-60724
 */

function progress_field_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    #kint($form);
}