<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * 修改Drupal.Settings
 * HOOK_js_settings_alter
 */
function progress_field_js_settings_alter(array &$settings, AttachedAssetsInterface $assets) {
    # 去除删除按钮的X-Progress-ID参数，防止删除文件出错
    if(isset($settings['ajax'])) {
        foreach($settings['ajax'] as $k => $v) {
            if(strpos($k, 'remove-button') > 0) {
                $settings['ajax'][$k]['url'] = preg_replace('/\&X\-Progress\-ID\=\d+/', '', $v['url']);
            }
        }
    }
}
